name: Codecheck

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - 'main'
  push:
    branches:
      - "**"

permissions:
  contents: read
  actions: read
  checks: write

env:
  FLUTTER_TEST_REPORT: ${{github.workspace}}/dart-test-report.json

jobs:
  code_check:
    name: "Codecheck"
    runs-on: ubuntu-latest
    if: ${{ needs.setup.outputs.file-changed == 'true' || github.event_name == 'pull_request' }}
    timeout-minutes: 10
    steps:
      - name: "Codecheck"
        uses: arxdeus/github_workflows/actions/flutter_codecheck@main
        with:
          flutter-version: 3.44.7
          line-length: 80
