name: Dry Run

on:
  push:
    branches:
      - "release/**"
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
    branches:
      - 'main'
jobs:
  dry_publish:
    name: "Dry Publish - ${{ strategy.job-index }}"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout repository"
      uses: actions/checkout@v4
      with:
        fetch-tags: true
        fetch-depth: 0

    - name: "Setup Flutter"
      uses: arxdeus/github_workflows/actions/flutter_setup@main
      with:
        flutter-version: 3.44.7

    - name: "Run Dry Publish"
      shell: bash
      run: flutter pub publish --dry-run
